# Human purpose:
#   Retrieve the canonical JM105 Figure 4 Panel E external-context layout-fix outputs from Euler.
#
# Original source clue / conversation context:
#   Recovered from the 2026-07-06 Figure 4 V17D/V17E2 repair workflow. The original
#   PowerShell retrieval failure was caused by selecting a .tar.gz archive as the render
#   directory and then appending .tar.gz again. This helper uses exact explicit paths by default.
#
# Expected inputs:
#   - Remote render directory created by run-figure4-panel-e-external-context-euler.sh
#   - Matching remote archive at <remote render directory>.tar.gz
#
# Expected outputs:
#   - Local extracted folder under Downloads
#   - Fixed Panel E SVG/PDF/transparent PNG/white-preview PNG
#   - layout/transparency audits and locked-values TSV
#
# Known assumptions:
#   - Default paths point to the recovered V17E2 run from 2026-07-06.
#   - Edit $RemoteRenderDir and $RemoteArchive when retrieving a newer run.
#   - No raw microscopy or RNA-seq data are copied; only figure-render outputs and TSV audits.
#
# Data status:
#   Retrieves rendered output only. No biological data are generated by this script.

$ErrorActionPreference = "Stop"

$RemoteUser = "jmccarthy"
$RemoteHost = "euler.ethz.ch"
$RemoteRenderDir = "/cluster/scratch/jmccarthy/JM105_RNAseq/Figure4_PANEL_E_LAYOUT_FIX_V17E2_20260706_161136"
$RemoteArchive = "/cluster/scratch/jmccarthy/JM105_RNAseq/Figure4_PANEL_E_LAYOUT_FIX_V17E2_20260706_161136.tar.gz"

Write-Host "Remote render directory:"
Write-Host $RemoteRenderDir
Write-Host ""
Write-Host "Remote archive:"
Write-Host $RemoteArchive

$RemoteCheckCmd = "bash -lc 'test -d $RemoteRenderDir && test -s $RemoteArchive && test -s $RemoteRenderDir/panels/Figure4_panel_E_v17e2_clean.preview_white.png && test -s $RemoteRenderDir/panels/Figure4_panel_E_v17e2_clean.svg && test -s $RemoteRenderDir/panels/Figure4_panel_E_v17e2_clean.pdf && test -s $RemoteRenderDir/panels/Figure4_panel_E_v17e2_clean.transparent.png && test -s $RemoteRenderDir/audit/00_PANEL_E_LAYOUT_FIX_AUDIT.tsv && test -s $RemoteRenderDir/audit/09_TRANSPARENCY_AUDIT.tsv && test -s $RemoteRenderDir/derived_data/Figure4E_v17e2_locked_values.tsv && echo OK || { echo FAILED; echo DIRECTORY; ls -ld $RemoteRenderDir 2>&1; echo ARCHIVE; ls -lh $RemoteArchive 2>&1; echo FILES; find $RemoteRenderDir -maxdepth 2 -type f | sort 2>&1; }'"
$RemoteCheck = ssh "${RemoteUser}@${RemoteHost}" $RemoteCheckCmd
$RemoteCheckText = (($RemoteCheck | Out-String).Trim())

Write-Host ""
Write-Host "Remote check:"
Write-Host $RemoteCheckText

if (-not $RemoteCheckText.StartsWith("OK")) {
    throw "Remote Panel E check failed."
}

$Stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$LocalDest = "$env:USERPROFILE\Downloads\JM105_Figure4_PanelE_ExternalContext_$Stamp"
$LocalArchive = Join-Path $LocalDest "Figure4_PANEL_E_EXTERNAL_CONTEXT.tar.gz"
$ExtractDir = Join-Path $LocalDest "extracted"

New-Item -ItemType Directory -Force -Path $LocalDest | Out-Null
New-Item -ItemType Directory -Force -Path $ExtractDir | Out-Null

Write-Host ""
Write-Host "Downloading archive..."
scp "${RemoteUser}@${RemoteHost}:$RemoteArchive" "$LocalArchive"

if (-not (Test-Path $LocalArchive)) {
    throw "Archive did not download: $LocalArchive"
}

Write-Host ""
Write-Host "Extracting archive..."
tar.exe -xzf "$LocalArchive" -C "$ExtractDir"

$Preview = Get-ChildItem -Path $ExtractDir -Recurse -Filter "Figure4_panel_E_v17e2_clean.preview_white.png" | Select-Object -First 1
$Svg = Get-ChildItem -Path $ExtractDir -Recurse -Filter "Figure4_panel_E_v17e2_clean.svg" | Select-Object -First 1
$Pdf = Get-ChildItem -Path $ExtractDir -Recurse -Filter "Figure4_panel_E_v17e2_clean.pdf" | Select-Object -First 1
$Transparent = Get-ChildItem -Path $ExtractDir -Recurse -Filter "Figure4_panel_E_v17e2_clean.transparent.png" | Select-Object -First 1
$Audit = Get-ChildItem -Path $ExtractDir -Recurse -Filter "00_PANEL_E_LAYOUT_FIX_AUDIT.tsv" | Select-Object -First 1
$Transparency = Get-ChildItem -Path $ExtractDir -Recurse -Filter "09_TRANSPARENCY_AUDIT.tsv" | Select-Object -First 1
$Values = Get-ChildItem -Path $ExtractDir -Recurse -Filter "Figure4E_v17e2_locked_values.tsv" | Select-Object -First 1

Write-Host ""
Write-Host "Retrieved to:"
Write-Host $LocalDest

Write-Host ""
Write-Host "Key files:"
if ($Preview) { Write-Host "  Preview:          $($Preview.FullName)" } else { Write-Host "  Preview:          MISSING" }
if ($Svg) { Write-Host "  SVG:              $($Svg.FullName)" } else { Write-Host "  SVG:              MISSING" }
if ($Pdf) { Write-Host "  PDF:              $($Pdf.FullName)" } else { Write-Host "  PDF:              MISSING" }
if ($Transparent) { Write-Host "  Transparent PNG:  $($Transparent.FullName)" } else { Write-Host "  Transparent PNG:  MISSING" }
if ($Audit) { Write-Host "  Layout audit:     $($Audit.FullName)" } else { Write-Host "  Layout audit:     MISSING" }
if ($Transparency) { Write-Host "  Transparency:     $($Transparency.FullName)" } else { Write-Host "  Transparency:     MISSING" }
if ($Values) { Write-Host "  Locked values:    $($Values.FullName)" } else { Write-Host "  Locked values:    MISSING" }

Write-Host ""
Write-Host "Transparency audit:"
if ($Transparency) {
    Import-Csv -Delimiter "`t" $Transparency.FullName | Format-Table -AutoSize
}

if ($null -eq $Preview) {
    throw "Panel E preview PNG was not found after extraction."
}

Start-Process $Preview.FullName
Start-Process $LocalDest
